jenkins:
  systemMessage: "DevOps Multi-Tier Application CI/CD Server"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
          
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
  
  dockerTool:
    installations:
      - name: "docker"
        properties:
          - installSource:
              installers:
                - fromDocker:
                    version: "latest"

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@devops.local"
  
  globalLibraries:
    libraries:
      - name: "shared-library"
        retriever:
          modernSCM:
            scm:
              filesystem:
                path: "/var/jenkins_home/shared-library"
                clearWorkspace: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "docker-hub"
              username: "your-dockerhub-username"
              password: "your-dockerhub-password"
              description: "Docker Hub Credentials"
          - usernamePassword:
              scope: GLOBAL
              id: "github"
              username: "your-github-username"
              password: "your-github-token"
              description: "GitHub Credentials"
          - string:
              scope: GLOBAL
              id: "aws-access-key"
              secret: "your-aws-access-key"
              description: "AWS Access Key"
          - string:
              scope: GLOBAL
              id: "aws-secret-key"
              secret: "your-aws-secret-key"
              description: "AWS Secret Key"

jobs:
  - script: >
      pipelineJob('backend-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('/var/jenkins_home/workspace/cicd-aws')
                }
                branches('*/main')
              }
            }
            scriptPath('jenkins/Jenkinsfile.backend')
          }
        }
        triggers {
          pollSCM('H/5 * * * *')
        }
      }
  - script: >
      pipelineJob('frontend-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('/var/jenkins_home/workspace/cicd-aws')
                }
                branches('*/main')
              }
            }
            scriptPath('jenkins/Jenkinsfile.frontend')
          }
        }
        triggers {
          pollSCM('H/5 * * * *')
        }
      }
